# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- script: |
   - checkout: self
   - checkout: https://github.com/JeenaFrancis/Owasp-Zap.git
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- task: CmdLine@2
  inputs:
    script: |
      docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t https://example.com -r baseline-scan-report.html
      true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/baseline-scan-report.html'
    ArtifactName: 'Report'
    publishLocation: 'Container'
